DROP DATABASE IF EXISTS events;

CREATE DATABASE events;

\c events;

CREATE TABLE events (
  id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
  user_id VARCHAR ( 50 ) NOT NULL,
  title VARCHAR ( 100 ),
  start_time VARCHAR ( 5 ),
  end_time VARCHAR ( 5 ),
  body VARCHAR ( 1000 ),
  date date
);


INSERT INTO events (user_id, title, start_time, end_time, body, date) values ('6170fd26078b5453c9461402', 'Event Three', '21:20' ,'21:25', 'This is the body', '10/23/2021');

INSERT INTO events (user_id, title, start_time, end_time, body, date) values ('6170fd26078b5453c9461402', 'Event Two', '21:30', '21:35', 'This is the body', '10/23/2021');

INSERT INTO events (user_id, title, start_time, end_time, body, date) values ('6170fd26078b5453c9461402', 'Event One', '21:40', '21:45', 'This is the body', '10/23/2021');

INSERT INTO events (user_id, title, start_time, end_time, body, date) values ('6170fd26078b5453c9461402', 'Event Five', '21:50', '21:55', 'This is the body', '10/23/2021');

INSERT INTO events (user_id, title, start_time, end_time, body, date) values ('6170fd26078b5453c9461402', 'Event Four', '22:00', '22:05', 'This is the body', '10/23/2021');