DROP DATABASE IF EXISTS joblisting;

CREATE DATABASE joblisting;

\c joblisting;

CREATE TABLE joblisting (
  id int GENERATED BY DEFAULT AS IDENTITY  PRIMARY KEY,
  job_id int NOT NULL,
  url VARCHAR ( 250 ),
  title VARCHAR ( 250 ),
  company_name VARCHAR ( 250 ),
  category VARCHAR ( 20 ),
  job_type VARCHAR ( 20 ),
  publication_date date,
  candidate_required_location VARCHAR ( 50 ),
  salary VARCHAR ( 250 ),
  description TEXT NOT NULL,
  company_logo_url VARCHAR ( 250 ),
  tags VARCHAR ( 250 ),
  isLiked boolean default false
);

copy joblisting (job_id, url, title, company_name, category, job_type, publication_date, candidate_required_location, salary, description, company_logo_url, tags)
FROM '/Users/jaylee/response2.csv'
DELIMITER ','
CSV HEADER;

create index job_id_index
on joblisting(job_id);